-- 1. جدول الأقسام (Categories)
create table categories (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text unique not null,
  -- filter_schema defines the allowed filters/attributes for this category
  -- Example: [{"key": "color", "label": "Color", "type": "text"}, {"key": "size", "label": "Size", "type": "select", "options": ["S", "M", "L"]}]
  filter_schema jsonb default '[]'::jsonb 
);

-- 2. جدول المنتجات (Products)
create table products (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  price numeric not null,
  stock integer not null default 0,
  category_id bigint references categories(id),
  images text[],
  -- specs stores the variable attributes based on the category's filter_schema
  -- Example: {"color": "Red", "size": "M"}
  specs jsonb default '{}'::jsonb 
);

-- Index for fast JSONB filtering
create index idx_products_specs on products using gin (specs);

-- Enable Row Level Security
alter table categories enable row level security;
alter table products enable row level security;

-- Policies
create policy "Public categories are viewable by everyone" 
  on categories for select using (true);

create policy "Admins can manage categories" 
  on categories for all using (auth.role() = 'authenticated');

create policy "Public products are viewable by everyone" 
  on products for select using (true);

create policy "Admins can manage products" 
  on products for all using (auth.role() = 'authenticated');
